# Generated by Django 3.2.5 on 2021-10-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_buyingpower_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyingpower',
            old_name='username',
            new_name='user_id',
        ),
    ]
