# Generated by Django 3.2.5 on 2021-10-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_username_buyingpower_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyingpower',
            old_name='user_id',
            new_name='user',
        ),
    ]
