# Generated by Django 3.2.5 on 2021-11-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_username_watchlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='username',
            new_name='user',
        ),
    ]
