# Generated by Django 3.2.5 on 2021-12-29 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_username_portfolio_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=5)),
                ('date', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=6)),
                ('units', models.IntegerField()),
                ('price', models.FloatField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
